### ISSUE TITLE
site is down

### ISSUE THREAD

**Issue by mjhea0** [django/djangosnippets.org#133] opened 2020-06-17 18:43 UTC
The site has been down since June 12th.

https://twitter.com/testdrivenio/status/1271417801480327169

<img width="1424" alt="Application_Error" src="https://user-images.githubusercontent.com/2018167/84936874-8a505d80-b0a0-11ea-914e-75fd1917192f.png">

**Comment by carltongibson** [comment] 2020-06-17 19:02
@mjhea0 Thanks for the report. Will have a look tomorrow.

**Comment by MarkusH** [comment] 2020-06-17 21:32
Should be fixed by #141. I'm currently waiting for Travic CI to report back the test status.

The error on Heroku is this:
```
2020-06-17T21:08:22.217392+00:00 app[web.1]: Traceback (most recent call last):
2020-06-17T21:08:22.217399+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
2020-06-17T21:08:22.217400+00:00 app[web.1]:     worker.init_process()
2020-06-17T21:08:22.217400+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 160, in init_process
2020-06-17T21:08:22.217401+00:00 app[web.1]:     self.patch()
2020-06-17T21:08:22.217401+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 53, in patch
2020-06-17T21:08:22.217401+00:00 app[web.1]:     monkey.patch_all()
2020-06-17T21:08:22.217401+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gevent/monkey.py", line 1202, in patch_all
2020-06-17T21:08:22.217402+00:00 app[web.1]:     _notify_patch(events.GeventWillPatchAllEvent(modules_to_patch, kwargs), _warnings)
2020-06-17T21:08:22.217403+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gevent/monkey.py", line 184, in _notify_patch
2020-06-17T21:08:22.217403+00:00 app[web.1]:     notify_and_call_entry_points(event)
2020-06-17T21:08:22.217404+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/gevent/events.py", line 104, in notify_and_call_entry_points
2020-06-17T21:08:22.217405+00:00 app[web.1]:     subscriber = plugin.load()
2020-06-17T21:08:22.217405+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2323, in load
2020-06-17T21:08:22.217405+00:00 app[web.1]:     self.require(*args, **kwargs)
2020-06-17T21:08:22.217405+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in require
2020-06-17T21:08:22.217406+00:00 app[web.1]:     items = working_set.resolve(reqs, env, installer, extras=self.extras)
2020-06-17T21:08:22.217406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
2020-06-17T21:08:22.217407+00:00 app[web.1]:     raise VersionConflict(dist, req).with_context(dependent_req)
2020-06-17T21:08:22.217408+00:00 app[web.1]: pkg_resources.VersionConflict: (greenlet 0.4.15 (/app/.heroku/python/lib/python3.7/site-packages), Requirement.parse('greenlet>=0.4.16; platform_python_implementation == "CPython"'))
2020-06-17T21:08:22.217408+00:00 app[web.1]: [2020-06-17 21:08:22 +0000] [13] [INFO] Worker exiting (pid: 13)```

**Comment by carltongibson** [comment] 2020-06-18 06:55
OK, we're back up. Thanks all. 

Not at all sure why we're using gevent but... 🤔

**Comment by chriswedgwood** [comment] 2020-06-18 08:34
Apologies if this was one of my merges @carltongibson @MarkusH @mjhea0 
I tested it with the following docker and it all seemed to work. Im not so familiar with heroku or gevent but what was the version conflict with? Or what is the root issue here?  :
The docker environment I used to test has greenlet 0.4.15 and is working.
 ```
 web:
    build: .
    environment:
      - REDISTOGO_URL=redis://redis:6379/0
      - SECRET_KEY=p_o3vp1rg5)t^lxm9-43%0)s-=1qpeq%o7gfq+e4#*!t+_ev82
      - DEBUG=True
      - ALLOWED_HOSTS=0.0.0.0,127.0.0.1
      - DATABASE_URL=postgres://postgres:postgres@db/djangosnippets
      - DJANGO_SETTINGS_MODULE=djangosnippets.settings.production
      - SEARCHBOX_SSL_URL=http://elasticsearch:9200/
     

    command: gunicorn -b 0.0.0.0:8000 -k gevent -w 4 djangosnippets.wsgi:application
```

Things I'm thinking to resolve in future:

1) Check website after merges to master / setup some monitoring. Does the main django site use monitoring?
2) Would be good to know the production setup and perhaps replicate it with vagrant to capture these issues before merging?

**Comment by MarkusH** [comment] 2020-06-18 08:36
I _think_ it was caused by the update to gevent in #132 but didn't fully investigate. I only noticed, that there was a new greenlet version available and figured I'll bump that to fix it :man_shrugging: :smile:

**Closed** 2020-06-19 10:07 UTC
